### ISSUE TITLE
Does not auto install required package hyperclick

### ISSUE THREAD

**Issue by stefanbuck** [danielbayley/atom-hyperclick-octolinker#2]
Shouldn't installing this package also auto install the required `hyperclick` packages?

**Comment by danielbayley** [comment]
@stefanbuck It certainly should, since it [uses] _[package-deps]_. According to your other issue (#1), it actually did… It says `hyperclick 0.1.3`?

[uses]: https://github.com/danielbayley/atom-hyperclick-octolinker/blob/master/index.coffee#L6
[package-deps]: https://github.com/steelbrain/package-deps

**Comment by stefanbuck** [comment]
Sorry, forgot to tell, that I installed it manually afterwords

**Comment by danielbayley** [comment]
Ah ok, well actually this is just a symptom of #1, since the `activate` function is what triggers the install, so it simply didn’t run.

**Comment by stefanbuck** [comment]
Makes sense 👍  Btw thanks for writing the plugin. Looking forward to use it
